// lib/audienceData.js — Listening DNA + Discovery Flow data

/* ─── ARCHETYPES ─────────────────────────────────────────────── */
export const archetypes = [
  {
    id: 'binger',
    name: 'The Weekend Binger',
    emoji: '🛋️',
    color: '#ec4899',
    tagline: 'Blocks entire weekends for audio marathons',
    population: 2100000,
    populationPct: 11.4,
    d30Retention: 58.2,
    avgSessionMin: 94,
    avgShowsPerWeek: 3.4,
    conversionRate: 12.8,
    arpu: 127,
    peakHour: '9 PM',
    peakDays: ['Fri', 'Sat', 'Sun'],
    episodesPerSession: 4.8,
    daysActivePerWeek: 2.1,
    genreAffinity: [
      { genre: 'Romance', score: 95 },
      { genre: 'Drama', score: 88 },
      { genre: 'Comedy', score: 72 },
      { genre: 'Crime', score: 55 },
      { genre: 'Thriller', score: 61 },
      { genre: 'Horror', score: 44 },
      { genre: 'Mythology', score: 38 },
    ],
    // 24 values: hour 0 (midnight) → hour 23 (11pm)
    hourlyIntensity: [6, 4, 2, 1, 1, 1, 3, 8, 12, 18, 20, 18, 15, 12, 10, 9, 11, 16, 24, 48, 82, 95, 86, 62],
    conversionDrivers: [
      { trigger: 'Free 7-day trial popup', effectiveness: 91, color: '#10b981' },
      { trigger: 'Episode cliff-hanger gate', effectiveness: 84, color: '#6366f1' },
      { trigger: 'Weekend limited offer', effectiveness: 78, color: '#f59e0b' },
      { trigger: 'Series completion nudge', effectiveness: 65, color: '#06b6d4' },
    ],
    insights: [
      'Completes series 3× faster than platform average',
      'Sat 7–10pm push notifications: 41% open rate',
      'Churns sharply when a series ends — schedule next show immediately',
      'Responds 2× better to visual story trailers than text banners',
    ],
    topShows: ['Ishq Mein Marjawan', 'Crime Patrol Stories', 'Raat Ka Safar'],
  },
  {
    id: 'commuter',
    name: 'The Daily Commuter',
    emoji: '🚆',
    color: '#6366f1',
    tagline: 'Fills commute time, Mon–Fri, like clockwork',
    population: 4800000,
    populationPct: 26.2,
    d30Retention: 44.7,
    avgSessionMin: 31,
    avgShowsPerWeek: 1.8,
    conversionRate: 8.4,
    arpu: 84,
    peakHour: '8 AM',
    peakDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    episodesPerSession: 1.4,
    daysActivePerWeek: 4.8,
    genreAffinity: [
      { genre: 'Crime', score: 90 },
      { genre: 'Thriller', score: 85 },
      { genre: 'Drama', score: 58 },
      { genre: 'Comedy', score: 64 },
      { genre: 'Romance', score: 42 },
      { genre: 'Horror', score: 38 },
      { genre: 'Mythology', score: 30 },
    ],
    hourlyIntensity: [2, 1, 1, 1, 2, 5, 18, 84, 92, 48, 22, 24, 42, 26, 18, 14, 10, 86, 94, 58, 22, 10, 5, 3],
    conversionDrivers: [
      { trigger: '"Continue where you left off" streak prompt', effectiveness: 88, color: '#10b981' },
      { trigger: 'Offline download feature unlock', effectiveness: 82, color: '#6366f1' },
      { trigger: 'Morning briefing personalisation', effectiveness: 74, color: '#f59e0b' },
      { trigger: 'Ad-free commute offer', effectiveness: 70, color: '#06b6d4' },
    ],
    insights: [
      'Opens app within 5 min of the same time every weekday',
      'Episode length 25–35 min has 38% better completion rate',
      'Drops on public holidays — expect 40% DAU dip',
      'Offline mode doubles this segment\'s D30 retention',
    ],
    topShows: ['Crime Patrol Stories', 'Kahaani', 'Ishq Mein Marjawan'],
  },
  {
    id: 'loyalist',
    name: 'The Mythology Loyalist',
    emoji: '🪔',
    color: '#f59e0b',
    tagline: 'Deep, focused listener — never skips, never rushes',
    population: 1640000,
    populationPct: 8.9,
    d30Retention: 71.4,
    avgSessionMin: 58,
    avgShowsPerWeek: 1.2,
    conversionRate: 18.6,
    arpu: 156,
    peakHour: '7 AM',
    peakDays: ['Sat', 'Sun', 'Mon'],
    episodesPerSession: 2.1,
    daysActivePerWeek: 5.4,
    genreAffinity: [
      { genre: 'Mythology', score: 98 },
      { genre: 'Drama', score: 72 },
      { genre: 'Romance', score: 34 },
      { genre: 'Crime', score: 28 },
      { genre: 'Thriller', score: 22 },
      { genre: 'Comedy', score: 18 },
      { genre: 'Horror', score: 12 },
    ],
    hourlyIntensity: [10, 6, 4, 3, 5, 12, 42, 68, 58, 52, 48, 45, 50, 55, 52, 48, 44, 42, 48, 52, 54, 48, 35, 18],
    conversionDrivers: [
      { trigger: 'Exclusive mythology series offer', effectiveness: 96, color: '#10b981' },
      { trigger: 'Festival / occasion themed content', effectiveness: 88, color: '#6366f1' },
      { trigger: 'HD narration quality unlock', effectiveness: 79, color: '#f59e0b' },
      { trigger: 'Scholar\'s notes & episode guides', effectiveness: 68, color: '#06b6d4' },
    ],
    insights: [
      'Highest D30 retention on platform — once hooked, almost never churns',
      'Morning listening 6–9am aligns with spiritual routines',
      'Ultra-loyal: will wait weeks for new episodes of a favourite series',
      'Strong word-of-mouth driver — refers 2.4 users per loyal member',
    ],
    topShows: ['Mahabharata Retold', 'Ramayana Retold', 'Bhagavad Gita Stories'],
  },
  {
    id: 'nightowl',
    name: 'The Late Night Explorer',
    emoji: '🌙',
    color: '#8b5cf6',
    tagline: 'Discovers new shows at midnight, binge-explores',
    population: 2860000,
    populationPct: 15.6,
    d30Retention: 38.1,
    avgSessionMin: 47,
    avgShowsPerWeek: 4.2,
    conversionRate: 6.8,
    arpu: 72,
    peakHour: '11 PM',
    peakDays: ['Thu', 'Fri', 'Sat'],
    episodesPerSession: 2.9,
    daysActivePerWeek: 3.2,
    genreAffinity: [
      { genre: 'Horror', score: 94 },
      { genre: 'Thriller', score: 88 },
      { genre: 'Crime', score: 76 },
      { genre: 'Mystery', score: 84 },
      { genre: 'Romance', score: 38 },
      { genre: 'Comedy', score: 30 },
      { genre: 'Mythology', score: 22 },
    ],
    hourlyIntensity: [68, 78, 72, 52, 30, 10, 5, 4, 3, 4, 6, 8, 10, 12, 10, 8, 12, 20, 30, 45, 62, 80, 88, 76],
    conversionDrivers: [
      { trigger: 'Exclusive horror series unlock', effectiveness: 85, color: '#10b981' },
      { trigger: 'Late night "For you" algorithm', effectiveness: 78, color: '#6366f1' },
      { trigger: '"Sleep timer" premium feature', effectiveness: 72, color: '#f59e0b' },
      { trigger: '3-episode preview pass', effectiveness: 60, color: '#06b6d4' },
    ],
    insights: [
      'Highest show variety — tries 4+ shows per week but commits to few',
      '11pm–1am window: 3× higher push open rate than daytime',
      'Churns when horror content runs low — content calendar gaps hurt this segment',
      'High "discovery" behaviour: algorithm recommendations work well here',
    ],
    topShows: ['Raat Ka Safar', 'Kahaani', 'Crime Patrol Stories'],
  },
  {
    id: 'poweruser',
    name: 'The Premium Powerhouse',
    emoji: '💎',
    color: '#10b981',
    tagline: 'Cross-genre super fan — your best customer',
    population: 1355000,
    populationPct: 7.4,
    d30Retention: 88.4,
    avgSessionMin: 112,
    avgShowsPerWeek: 5.8,
    conversionRate: 100,
    arpu: 214,
    peakHour: 'All day',
    peakDays: ['Every day'],
    episodesPerSession: 6.2,
    daysActivePerWeek: 6.8,
    genreAffinity: [
      { genre: 'Romance', score: 82 },
      { genre: 'Crime', score: 88 },
      { genre: 'Mythology', score: 78 },
      { genre: 'Thriller', score: 84 },
      { genre: 'Horror', score: 72 },
      { genre: 'Comedy', score: 76 },
      { genre: 'Drama', score: 90 },
    ],
    hourlyIntensity: [22, 14, 8, 6, 5, 8, 22, 62, 72, 70, 68, 65, 68, 66, 64, 62, 65, 68, 70, 74, 76, 68, 52, 36],
    conversionDrivers: [
      { trigger: 'Already converted — retention focus', effectiveness: 100, color: '#10b981' },
      { trigger: 'Annual plan loyalty discount', effectiveness: 92, color: '#6366f1' },
      { trigger: 'Gifting subscription feature', effectiveness: 84, color: '#f59e0b' },
      { trigger: 'Creator meet & greet access', effectiveness: 76, color: '#06b6d4' },
    ],
    insights: [
      'Already premium — focus is retention and upsell to annual plan',
      'Listens across ALL genres — content diversity keeps them subscribed',
      'Highest ARPU: ₹214/month vs platform avg ₹84.5',
      'Champion users: refer 4.1 new installs per quarter on average',
    ],
    topShows: ['All top shows in rotation'],
  },
];

/* ─── CROSS-SHOW DISCOVERY FLOW ─────────────────────────────── */

export const discoveryNodes = {
  sources: [
    { id: 'ishq',      label: 'Ishq Mein Marjawan', shortLabel: 'Ishq',        emoji: '💕', color: '#ec4899', value: 1240000 },
    { id: 'crime',     label: 'Crime Patrol Stories', shortLabel: 'Crime',      emoji: '🔍', color: '#6366f1', value: 980000  },
    { id: 'mahabharat',label: 'Mahabharata Retold',  shortLabel: 'Mahabharat', emoji: '🪔', color: '#f59e0b', value: 870000  },
    { id: 'kahaani',   label: 'Kahaani',             shortLabel: 'Kahaani',    emoji: '⚡', color: '#8b5cf6', value: 760000  },
    { id: 'raat',      label: 'Raat Ka Safar',       shortLabel: 'Raat',       emoji: '👻', color: '#ef4444', value: 640000  },
  ],
  destinations: [
    { id: 'premium',   label: '💎 Went Premium',    shortLabel: 'Premium',     color: '#10b981', value: 0 },
    { id: 'crime-d',   label: '🔍 Crime Patrol',    shortLabel: 'Crime',       color: '#6366f1', value: 0 },
    { id: 'ishq-d',    label: '💕 Ishq Mein...',    shortLabel: 'Ishq',        color: '#ec4899', value: 0 },
    { id: 'mahab-d',   label: '🪔 Mahabharata',     shortLabel: 'Mahab.',      color: '#f59e0b', value: 0 },
    { id: 'raat-d',    label: '👻 Raat Ka Safar',   shortLabel: 'Raat',        color: '#ef4444', value: 0 },
    { id: 'kahaani-d', label: '⚡ Kahaani',         shortLabel: 'Kahaani',     color: '#8b5cf6', value: 0 },
    { id: 'churned',   label: '👋 Churned',         shortLabel: 'Churned',     color: '#334155', value: 0 },
  ],
};

export const discoveryLinks = [
  // From Ishq (1,240,000 completers)
  { from: 'ishq', to: 'premium',   value: 422000, pct: 34.0, note: '🏆 Top premium driver' },
  { from: 'ishq', to: 'crime-d',   value: 298000, pct: 24.0, note: 'Genre crossover' },
  { from: 'ishq', to: 'mahab-d',   value: 223000, pct: 18.0 },
  { from: 'ishq', to: 'churned',   value: 297000, pct: 24.0 },

  // From Crime (980,000 completers)
  { from: 'crime', to: 'premium',  value: 294000, pct: 30.0, note: '2nd best premium driver' },
  { from: 'crime', to: 'ishq-d',   value: 206000, pct: 21.0 },
  { from: 'crime', to: 'kahaani-d',value: 186000, pct: 19.0 },
  { from: 'crime', to: 'raat-d',   value: 118000, pct: 12.0 },
  { from: 'crime', to: 'churned',  value: 176000, pct: 18.0 },

  // From Mahabharata (870,000 completers)
  { from: 'mahabharat', to: 'premium',  value: 357000, pct: 41.0, note: '🏆 Highest premium rate!' },
  { from: 'mahabharat', to: 'crime-d',  value: 157000, pct: 18.0 },
  { from: 'mahabharat', to: 'raat-d',   value: 130000, pct: 15.0 },
  { from: 'mahabharat', to: 'churned',  value: 226000, pct: 26.0 },

  // From Kahaani (760,000 completers)
  { from: 'kahaani', to: 'crime-d',   value: 213000, pct: 28.0 },
  { from: 'kahaani', to: 'raat-d',    value: 167000, pct: 22.0 },
  { from: 'kahaani', to: 'premium',   value: 106000, pct: 14.0 },
  { from: 'kahaani', to: 'churned',   value: 274000, pct: 36.0, note: '⚠️ High churn' },

  // From Raat Ka Safar (640,000 completers)
  { from: 'raat', to: 'kahaani-d', value: 154000, pct: 24.0 },
  { from: 'raat', to: 'crime-d',   value: 128000, pct: 20.0 },
  { from: 'raat', to: 'premium',   value: 141000, pct: 22.0 },
  { from: 'raat', to: 'churned',   value: 217000, pct: 34.0 },
];

// Which show is the best "gateway to premium"
export const gatewayInsights = [
  { show: 'Mahabharata Retold', premiumRate: 41.0, color: '#f59e0b', emoji: '🪔', rank: 1, note: 'Deep storytelling builds highest intent to pay' },
  { show: 'Ishq Mein Marjawan', premiumRate: 34.0, color: '#ec4899', emoji: '💕', rank: 2, note: 'Volume leader — most absolute premium conversions' },
  { show: 'Crime Patrol Stories', premiumRate: 30.0, color: '#6366f1', emoji: '🔍', rank: 3, note: 'Episodic format drives consistent subscriptions' },
  { show: 'Raat Ka Safar', premiumRate: 22.0, color: '#ef4444', emoji: '👻', rank: 4, note: 'Horror fans value ad-free experience most' },
  { show: 'Kahaani', premiumRate: 14.0, color: '#8b5cf6', emoji: '⚡', rank: 5, note: '⚠️ Low premium rate AND high churn — needs intervention' },
];
